---

- name: Install docker dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - gnupg2
    - apt-transport-https

- name: Trust docker repo key
  become: true
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add docker's apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker & python3-pip
  apt:
    name:
      - python3-setuptools
      - python3-pip
      - docker-ce
    state: latest

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Clone docker configuration
  git:
    repo: "{{ docker_configuration_repo }}"
    dest: "{{ dockers_files_dir }}"
    force: yes
    clone: yes
    update: yes

- name: Configure docker containers
  docker_services:
    project_src:  "{{ dockers_files_dir }}"
    build: yes
    pull: yes
    recreate: always
    state: present
