---

- hosts:
    - vepcon
  any_errors_fatal: true
  roles:
    - { role: common, become: yes, become_method: sudo, tags: common }
    - { role: python, become: yes, become_method: sudo, tags: python }
    - { role: docker-compose, tags: docker_compose }
    - { role: chatbot, tags: chatbot }
