---

- hosts:
    - vepcon
  any_errors_fatal: true
  roles:
    - { role: common, become: yes, become_method: sudo, tags: common }
    - { role: docker-compose, tags: docker }
    - { role: epcon-apps, tags: apps }
    - { role: nginx, tags: nginx }
