---

- name: poll incoming emails
  cron:
    name: "poll emails for helpdesk"
    job: "docker exec webarch_helpdesk_1 /usr/src/helpdesk/manage.py get_email 1>/dev/null 2>/dev/null"
    state: present

- name: Restart mail server once a night to catch up with cert changes
  cron:
    name: "mail restart"
    minute: "32"
    hour: "22"
    job: "cd /home/webarch; /usr/local/bin/docker-compose restart mail 1>/dev/null 2>/dev/null"
    state: present

- name: Train SpamAssassin
  cron:
    name: "train spamassassin"
    minute: "0"
    hour: "3"
    job: "docker exec webarch_mail_1 sa-learn --spam /var/mail/europython.io/helpdesk/.Junk --dbpath /var/mail-state/lib-amavis/.spamassassin"
    state: present
