---

- name: Install python
  apt:
    name:
      - python3-dev
      - python3-pip

- name: Update pip and setuptools
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - pip
    - setuptools
