---

- name: Install python
  apt:
    name: '{{ packages }}'
  vars:
    packages:
    - python-dev
    - python-setuptools
    - python-pip

- name: Update pip and setuptools
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - pip
    - setuptools
