---

- name: Install python
  apt:
    name: '{{ packages }}'
  vars:
    packages:
    - python3-dev
    - python3-setuptools
    - python3-pip

- name: Update pip and setuptools
  pip:
    name: '{{ item }}'
    state: latest
    executable: pip3
  with_items:
    - pip
    - setuptools
