---

- name: Install some apt packages
  apt:
    name: '{{ packages }}'
  vars:
    packages:
    - python-dev
    - python-pip

- name: Update pip and setuptools
  pip:
    name: '{{ item }}'
    state: forcereinstall
  with_items:
    - pip
    - setuptools
