---

- name: Install dependencies
  apt:
    name:
      - build-essential
      - libssl-dev
      - python-dev
      - python-pip
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  become_method: sudo

- name: Install docker-compose
  command:
    pip install --user docker-compose==1.22.0
  args:
    creates: "{{ home_dir }}/.local/bin/docker-compose"
