---

- name: Install docker dependencies
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Fetch Docker’s official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: docker_apt.key
    validate_certs: false

- name: Add Docker’s official GPG key
  apt_key:
    file: docker_apt.key
    state: present

- name: Add Docker's official APT repository
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name:
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - docker-ce

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Change a few ownerships to root:docker
  file:
    path: '{{ item }}'
    owner: root
    group: docker
  with_items:
    - /var/run/docker.sock
    - /usr/bin/docker

- name: Restart the docker daemon
  service:
    name: docker
    state: restarted
