---

- name: Install dependencies
  apt:
    name:
    - build-essential
    - libssl-dev
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  become_method: sudo

- name: Install docker-compose
  pip:
    name: docker-compose
    extra_args: --user
    version: 1.22.0
