---

- name: Install docker dependencies
  apt:
    name:
    - gnupg2
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    update_cache: yes
    cache_valid_time: 3600

- name: Trust Docker repository key
  become: true
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's official APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes
    cache_valid_time: 3600

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes

- name: Change a few ownerships to root:docker
  file:
    path: '{{ item }}'
    owner: root
    group: docker
  with_items:
    - /var/run/docker.sock
    - /usr/bin/docker

- name: Restart the docker daemon
  service:
    name: docker
    state: restarted
