---

- name: Install dependencies
  apt:
    name: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - build-essential
    - libssl-dev
    - python-dev
    - python-pip

- name: Install docker-compose
  pip:
    name: '{{ item }}'
    state: forcereinstall
  with_items:
    - cryptography==2.3
    - docker-compose==1.22.0
  executable: pip3

- name: docker-compose.yml template file
  copy:
    src: docker-compose.yml
    dest: "{{ docker_compose_filepath }}"
    owner: "{{ user }}"
    group: "docker"
    mode: 0640
