---

- include_tasks: install_docker.yml
  tags: [docker, docker_compose]

- include_tasks: install_docker_compose.yml
  tags: [docker, docker_compose]

- include_tasks: folders.yml
  tags: [docker, docker_compose]

- name: Create folders for docker-compose
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  with_items:
    - '{{ dockers_files_dir }}'
    - '{{ dockers_volumes_dir }}'
    - '{{ dockers_config_dir }}'
    - '{{ dockers_env_dir }}'
