---

- import_tasks: install_docker.yml
  become: yes
  become_method: sudo
  tags: docker

- name: Install docker-compose dependencies
  apt:
    name:
    - build-essential
    - libssl-dev
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  become_method: sudo
  tags: docker_compose

- name: Install docker-compose
  pip:
    name: docker-compose
    extra_args: --user
    version: 1.22.0
