---

- name: Clone docker configuration
  git:
    repo: "{{ docker_configuration_repo }}"
    dest: "{{ epcon_docker_apps_dir }}"
    force: yes
    clone: yes
    update: yes

- name: Create apps folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    recurse: yes
  with_items:
    - "{{ epcon_config_dir }}"
    - "{{ epcon_scripts_dir }}"
    - "{{ containers_env_files_dir }}"

- name: Copy the docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ epcon_apps_docker_compose_file }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0600

# - include_tasks: venv_files.yml
#   tags: venv_files

# - include_tasks: letsencrypt.yml
#   tags: letsencrypt, ssl
#
# - include_tasks: wiki.yml
#   tags: wiki
#
# - include_tasks: chatbot.yml
#   tags: chatbot, bot

# - name: Configure docker containers
#   docker_service:
#     project_src:  "{{ epcon_docker_apps_dir }}"
#     build: yes
#     pull: yes
#     recreate: always
#     state: present
#
# - include_tasks: cronjobs.yml
#   tags: cron

# - include_tasks: cronjobs.yml
#   tags: cronjobs, cron
