---

- name: Clone docker configuration
  git:
    repo: "{{ docker_configuration_repo }}"
    dest: "{{ epcon_docker_apps_dir }}"
    force: yes
    clone: yes
    update: yes

- include_tasks: venv_files.yml
  tags: venv_files

- include_tasks: cronjobs.yml
  tags: cronjobs, cron

# - name: copy the config templates
#
# - name: copy the config files
#
# - name: copy the scripts


# - name: Configure docker containers
#   docker_service:
#     project_src:  "{{ epcon_docker_apps_dir }}"
#     build: yes
#     pull: yes
#     recreate: always
#     state: present
#
# - include_tasks: cronjobs.yml
#   tags: cron
