---

user: "root"
group: "{{ ansible_ssh_user }}"

home_dir: '/home/{{ user }}'

tmp_install_dir: '{{ home_dir }}/tmp'
install_dir: '{{ home_dir }}/apps'
bin_dir: '{{ home_dir }}/bin'

config_dir_basename: "config"
env_dir_basename: "envfile"

dockers_files_dir: '{{ install_dir }}/dockerfile'
dockers_volumes_dir: '{{ install_dir }}/volume'
dockers_config_dir: '{{ install_dir }}/{{ config_dir_basename }}'
dockers_env_dir: '{{ install_dir }}/{{ env_dir_basename }}'

nginx_sites:
  - servername: ep2018.europython.eu
    proxy_pass: http://ep2018
    short_links:
      - from: ^/media/conference/sponsor/brochure/ep2018_sponsor_brochure.pdf
        to:   /media/TBD/europython2017-sponsor-brochure-compressed.pdf
      - from: ^/ep2018_sponsor_brochure.pdf
        to: /media/TBD/europython2017-sponsor-brochure-compressed.pdf
      - from: ^/volunteer-app
        to:   https://signup.zone/EDyBYYK7QSi7zMLK7
      - from: ^/mobile-app
        to:   https://attendify.com/app/u77swu/
    locations:
      - name: /static
        alias: /usr/src/ep2018/data/static
      - name: /media
        alias: /usr/src/ep2018/data/media_public
      - name: /media_public
        alias: /usr/src/ep2018/data/media_public
      - name: /media_private
        alias: /usr/src/ep2018/data/media_private
      - name: /ep-ticket-search-app
        alias: /usr/src/ep2018/ep-ticket-search-app
        auth:
          basic: EuroPython 2018 Ticket Search App
          basic_user_file: /etc/nginx/.htpasswd
    
    
  - servername: ep2017.europython.eu
    proxy_pass: http://ep2017
    short_links:
      - from: ^/media/conference/sponsor/brochure/ep2017_sponsor_brochure.pdf
        to:   /media/filer_public/db/f0/dbf03a1f-5ebf-4dfb-b555-595e86a6fa7d/europython2017-sponsor-brochure-compressed.pdf
      - from: ^/ep2017_sponsor_brochure.pdf
        to:   /media/filer_public/db/f0/dbf03a1f-5ebf-4dfb-b555-595e86a6fa7d/europython2017-sponsor-brochure-compressed.pdf
      - from: ^/volunteer-app
        to:   https://signup.zone/WmCunmZz7Nw4X9oLt/
      - from: ^/mobile-app
        to:   https://attendify.com/app/yh3g1w/
    locations:
      - name: /static
        alias: /usr/src/ep2017/data/static
      - name: /media
        alias: /usr/src/ep2017/data/media_public
      - name: /media_public
        alias: /usr/src/ep2017/data/media_public
      - name: /media_private
        alias: /usr/src/ep2017/data/media_private
      - name: /ep-ticket-search-app
        alias: /usr/src/ep2017/ep-ticket-search-app
        auth:
          basic: EuroPython 2017 Ticket Search App
          basic_user_file: /etc/nginx/.htpasswd
      - name: /ep-social-ticket-search-app
        alias: /usr/src/ep2017/ep-social-ticket-search-app
        auth:
          basic: EuroPython 2017 Social Ticket Search App
          basic_user_file: /etc/nginx/.htpasswd
    disable_accounts: True
    
  - servername: ep2016.europython.eu
    proxy_pass: http://ep2016
    short_links:
      - from: ^/ep2016_sponsor_brochure.pdf
        to:   /media/conference/sponsor/brochure/ep2016_sponsor_brochure.pdf
    locations:
      - name: /static
        alias: /usr/src/ep2016/data/static
      - name: /media
        alias: /usr/src/ep2016/data/media_public
      - name: /media_public
        alias: /usr/src/ep2016/data/media_public
      - name: /media_private
        alias: /usr/src/ep2016/data/media_private
 
    disable_accounts: True
    
  - servername: ep2015.europython.eu
    proxy_pass: http://ep2015
    short_links:
      - from: ^/ep2015_sponsor_brochure.pdf
        to:   /media/conference/sponsor/brochure/ep2015_sponsor_brochure.pdf last
    locations:
      - name: /static
        alias: /usr/src/ep2015/data/static
      - name: /media
        alias: /usr/src/ep2015/data/media_public
      - name: /media_public
        alias: /usr/src/ep2015/data/media_public
      - name: /media_private
        alias: /usr/src/ep2015/data/media_private
      - name: /.well-known
        alias: /usr/src/ep2015/data/.well-known
    disable_accounts: True
    
  - servername: epstage.europython.eu
    proxy_pass: http://epstage
    locations:
      - name: /static
        alias: /usr/src/epstage/data/static
      - name: /media
        alias: /usr/src/epstage/data/media_public
      - name: /media_public
        alias: /usr/src/epstage/data/media_public
      - name: /media_private
        alias: /usr/src/epstage/data/media_private
      - name: /ep-ticket-search-app
        alias: /usr/src/epstage/ep-ticket-search-app
        auth:
          basic: EuroPython Stage Ticket Search App
          basic_user_file: /etc/nginx/.htpasswd
      - name: /ep-social-ticket-search-app
        alias: /usr/src/epstage/ep-social-ticket-search-app
        auth:
          basic: EuroPython Stage Social Ticket Search App
          basic_user_file: /etc/nginx/.htpasswd
    disable_accounts: True
    
  - servername: dev.europython.eu
    redirected: https://ep2018.europython.eu
    short_links:
      - from: ^/\.well-known/acme-challenge/(.*)$
        to:   http://secure.europython.eu/.well-known/acme-challenge/$1 redirect
    disable_accounts: True
    
